### ISSUE TITLE
Change basic class organization to composable data types

### ISSUE THREAD

**Issue by naterush** [naterush/version-control#4]
Currently, our formats leave a lot to be desired. Ideally, a developer is going to want to specify a data format for their file, and have all operations automatically generated. As such, it doesn’t really make sense to have different operations for different files with the same underlying representations (e.g. any list should have the same operations defined on it). 

Here’s a proposal that accomplishes that:
- Have a base class File which stores: file_name, permanent_file_id, file_type. file_name is the only dynamic field. 
- Have subclasses responsible for implementation “file_contents”
    - file_contents must have a type specification: a list of lists, or something.

**Comment by aarondr77** [comment]
Addressed.
