### ISSUE TITLE
Adding a row and column at the same time:

### ISSUE THREAD

**Issue by naterush** [naterush/version-control#9]
Consider the following CSV file:

```
Name, email
Nate, nate@gmail.com
```

And then the following new version of the above CSV file:

```
Name, email, age
Nate, nate@gmail.com, 100
Jim, jim@gmail.com, 1000
```

Clearly, we have inserted a row on the bottom of this document, and we have also inserted a column. However, our current algorithm will algorithm will return instead return that 3 paths have been added: the path to “age”, the path to “100” and the path to the final row.

If we instead change the algorithm to return the third row and the third column, we have the following problem: do we add “1000” multiple times or not? 

If we add 1000 during both operations, then even when we inverse the operation add column, the 1000 will remain in the file so the inverse of the add row operation will remove it for good. But this would leave the CSV file in an inconsistent state between operations, as the system is currently designed. 

Here are some possible solutions:

1. We create a notion of a “multi-op,” which is a collection of ops that can only execute as a whole. When this multi-op is running, we turn of any error checking (e.g. making sure you’re inserting into a row that exists). This requires a) a new class for multi-op, and b) separating validity checking from the actual execution of the operation, and c) increased work when it comes to the insertion and deletion functions (handling these special cases where we insert a column into an empty row). 
2. Take it as is. We are adding some elements in columns, and some rows. But we are not adding a row and also adding a column. This fits with a vision of “only one of one type of operation on a single element per patch” — which seems like maybe a reasonable notion. Disadvantage: it is adding a row and adding a column.
3. Change operations to never do any validation. Aka: you can insert into a column where this inserts into a row that does not exist (and then the row is created). This pairs well with allowing multi-dim lists to be non-rectangular. This “rectangularity” assumption should be fairly straight-forward to remove. 

I’m personally leaning towards (3), because it’s hard to know what “validation” means in the general case anyways. We could allow operations to define properties of the file that must hold before they can be applied (in the form of just a Boolean function on the file), but this seems like a v26 goal.

**Comment by aarondr77** [comment]
Addressed.
